import 'enums.dart';
import 'models.dart';
import 'simulator_error.dart';

abstract final class DemoCards {
  static const _pan = '•••• •••• •••• ';
  static final all = <DemoCard>[
    _card('visa-approved', 'Demo Visa Approved', 'Visa', '1001', 'green',
        CardInteractionMethod.contactless,
        scenario: SimulatorScenario.success),
    _card('mastercard-pin', 'Demo Mastercard PIN', 'Mastercard', '1002', 'blue',
        CardInteractionMethod.insert,
        pin: true),
    _card('pin-retry', 'Demo PIN Retry', 'Mastercard', '1003', 'blue',
        CardInteractionMethod.insert,
        pin: true, pinBehavior: PinBehavior.failOnceThenSuccess),
    _card('declined', 'Demo Declined', 'Visa', '1004', 'red',
        CardInteractionMethod.contactless,
        scenario: SimulatorScenario.transactionFailed),
    _card('insufficient-funds', 'Demo Insufficient Funds', 'Visa', '1005',
        'orange', CardInteractionMethod.insert,
        scenario: SimulatorScenario.transactionFailed),
    _card('expired', 'Demo Expired Card', 'Visa', '1006', 'gray',
        CardInteractionMethod.insert,
        scenario: SimulatorScenario.transactionFailed),
    _card('unsupported', 'Demo Unsupported Card', 'Unknown', '1007', 'gray',
        CardInteractionMethod.contactless,
        methods: {PaymentMethod.bank},
        scenario: SimulatorScenario.unsupportedPaymentMethod),
    _card('contactless-fallback', 'Demo Contactless Fallback', 'Visa', '1008',
        'blue', CardInteractionMethod.contactless,
        scenario: SimulatorScenario.success),
    _card('refund', 'Demo Refund Card', 'Mastercard', '1009', 'green',
        CardInteractionMethod.insert),
    _card('szep', 'Demo SZÉP Card', 'SZÉP', '1010', 'green',
        CardInteractionMethod.contactless,
        methods: {PaymentMethod.szep}, scenario: SimulatorScenario.success),
    _card('ep', 'Demo EP Card', 'EP', '1011', 'lime',
        CardInteractionMethod.contactless,
        methods: {PaymentMethod.ep}, scenario: SimulatorScenario.success),
    _card('signature', 'Demo Signature Card', 'Visa', '1012', 'black',
        CardInteractionMethod.insert,
        signature: true),
  ];
  static DemoCard _card(String id, String name, String type, String last4,
          String variant, CardInteractionMethod method,
          {bool pin = false,
          bool signature = false,
          Set<PaymentMethod>? methods,
          SimulatorScenario scenario = SimulatorScenario.success,
          PinBehavior pinBehavior = PinBehavior.correct}) =>
      DemoCard(
          id: id,
          displayName: name,
          cardholderName: 'DEMO CARDHOLDER',
          maskedPan: '$_pan$last4',
          last4: last4,
          cardType: type,
          visualVariant: variant,
          interactionMethod: method,
          supportedPaymentMethods: methods ?? {PaymentMethod.bank},
          requiresPin: pin,
          correctPin: pin ? '1234' : null,
          pinBehavior: pin ? pinBehavior : PinBehavior.notRequired,
          defaultScenario: scenario,
          requireSignature: signature,
          expiryLabel: '12/99',
          developerNotes: 'Fictional simulator card.');
}

abstract final class ScenarioPresets {
  static final all = <ScenarioPreset>[
    _p('approved-contactless', 'Approved contactless',
        SimulatorScenario.success),
    _p('approved-chip-pin', 'Approved chip and PIN', SimulatorScenario.success,
        pin: true),
    _p('wrong-pin', 'Wrong PIN then approved', SimulatorScenario.success,
        pin: true, pinBehavior: PinBehavior.failOnceThenSuccess),
    _p('pin-blocked', 'PIN blocked', SimulatorScenario.transactionFailed,
        pin: true, pinBehavior: PinBehavior.blocked, error: 2000),
    _p('cancelled', 'Customer cancelled', SimulatorScenario.userCancelled,
        error: 1004),
    _p('rejected', 'Payment rejected', SimulatorScenario.transactionFailed,
        error: 2000),
    _p('insufficient', 'Insufficient funds',
        SimulatorScenario.transactionFailed,
        error: 2000),
    _p('busy', 'Terminal busy', SimulatorScenario.terminalBusy,
        before: TerminalStatus.busy, during: TerminalStatus.busy, error: 1011),
    _p('timeout', 'Network timeout', SimulatorScenario.requestTimeout,
        error: 3012),
    _p('expired-session', 'Session expired', SimulatorScenario.sessionExpired,
        error: 3004),
    _p('permission', 'Permission denied', SimulatorScenario.permissionDenied,
        error: 1102),
    _p('invalid-amount', 'Invalid amount', SimulatorScenario.invalidAmount,
        error: 1002),
    _p('tip-not-allowed', 'Tip not allowed', SimulatorScenario.tipNotAllowed,
        error: 1005),
    _p('tip-limit', 'Tip exceeds limit', SimulatorScenario.tipExceedsLimit,
        error: 1012),
    _p('refund-success', 'Refund successful', SimulatorScenario.success),
    _p('refund-failed', 'Refund failed', SimulatorScenario.refundFailed,
        error: 2001),
    _p('void-success', 'Void successful', SimulatorScenario.success),
    _p('void-failed', 'Void failed', SimulatorScenario.voidFailed, error: 2002),
    _p('terminated', 'App terminated', SimulatorScenario.appTerminated,
        error: 1010),
    _p('recovery', 'Recovery required', SimulatorScenario.networkError,
        error: 3013),
  ];
  static ScenarioPreset _p(String id, String name, SimulatorScenario scenario,
      {bool pin = false,
      PinBehavior pinBehavior = PinBehavior.notRequired,
      TerminalStatus before = TerminalStatus.ready,
      TerminalStatus during = TerminalStatus.busy,
      int? error}) {
    final e = error == null ? null : ErrorCatalog.lookup(error);
    return ScenarioPreset(
        id: id,
        name: name,
        description: 'Expected UI result: $name.',
        scenario: scenario,
        delay: Duration.zero,
        terminalStatusBefore: before,
        terminalStatusDuring: during,
        terminalStatusAfter: TerminalStatus.ready,
        requiresPin: pin,
        pinBehavior: pinBehavior,
        requireSignature: false,
        processor: 'HelloPay Simulator',
        responseErrorCode: e?.code.toString(),
        responseErrorMessage: e?.userMessage,
        receiptEnabled: true);
  }
}
